{{- if .Values.local.minio.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ $.Release.Namespace }}
data:
  rootUser: dmFsdWUtMg0KDQo=
  rootPassword: dmFsdWUtMg0KDQo=
{{- end }}