namespacesToMonitor:
- loki

local:
  grafana:
    enabled: true
  logs:
    enabled: true
  metrics:
    enabled: true
  traces:
    enabled: true
  minio:
    enabled: true

cloud:
  logs:
    enabled: false
    secret: logs
  metrics:
    enabled: false
    secret: metrics
  traces:
    enabled: false
    secret: traces

grafana:
  ingress:
    hosts:
      - host: monitoring.example.com
        paths:
          - path: /
            pathType: Prefix

