namespacesToMonitor:
- loki
- mimir
- tempo
clusterName: "observability"

loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1
    extraArgs: ["-log.level=debug"]
  monitoring:
    dashboards:
      enabled: false
    rules:
      enabled: false
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
  test:
    enabled: false

grafana-agent:
  agent:
    configMap:
      create: false
      name: "agent-configmap"
      key: 'config.river'

# mimir-distributed:
