---
name: Check for dependency updates

on:
    workflow_dispatch:
    schedule:
      # Run once a day
      - cron: '0 7 * * *'

permissions:
    contents: "write"
    pull-requests: "write"

env:
    UPDATECLI_CONFIG_DIR: "${{ github.workspace }}/.github/configs/updatecli.d"
    UPDATECLI_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
    updateLoki:
        name: Update the Loki subchart
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Updatecli
              uses: updatecli/updatecli-action@v2

            - name: Run Updatecli
              id: update-loki
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/loki.yaml
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                fi

            - name: Create pull request
              if: steps.update-loki.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "[dependency] Update the Loki subchart"
                body: "Updates the Loki subchart"
                base: main
                author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
                committer: "GitHub <noreply@github.com>"
                commit-message: Update loki
                labels: dependencies
                branch: chore/update-loki
                delete-branch: true

    updateGrafanaAlloy:
        name: Update the Grafana Alloy subchart
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Updatecli
              uses: updatecli/updatecli-action@v2

            - name: Run Updatecli
              id: update-grafana-alloy
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/alloy.yaml
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                fi

            - name: Create pull request
              if: steps.update-grafana-alloy.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "[dependency] Update the Grafana Alloy subchart"
                body: "Updates the Grafana Alloy subchart"
                base: main
                author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
                committer: "GitHub <noreply@github.com>"
                commit-message: Update Grafana Alloy
                labels: dependencies
                branch: chore/update-grafana-alloy
                delete-branch: true

    updateMimirDistributed:
        name: Update the Mimir Distributed subchart
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Updatecli
              uses: updatecli/updatecli-action@v2

            - name: Run Updatecli
              id: update-mimir-distributed
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/mimir-distributed.yaml
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                fi

            - name: Create pull request
              if: steps.update-mimir-distributed.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "[dependency] Update the Mimir Distributed subchart"
                body: "Updates the Mimir Distributed subchart"
                base: main
                author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
                committer: "GitHub <noreply@github.com>"
                commit-message: Update Mimir Distributed
                labels: dependencies
                branch: chore/update-mimir-distributed
                delete-branch: true

    updateTempoDistributed:
        name: Update the Tempo Distributed subchart
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Updatecli
              uses: updatecli/updatecli-action@v2

            - name: Run Updatecli
              id: update-tempo-distributed
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/tempo-distributed.yaml
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                fi

            - name: Create pull request
              if: steps.update-tempo-distributed.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "[dependency] Update the Tempo Distributed subchart"
                body: "Updates the tempo Distributed subchart"
                base: main
                author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
                committer: "GitHub <noreply@github.com>"
                commit-message: Update Tempo Distributed
                labels: dependencies
                branch: chore/update-tempo-distributed
                delete-branch: true

    updateMinio:
        name: Update the Minio subchart
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Updatecli
              uses: updatecli/updatecli-action@v2

            - name: Run Updatecli
              id: update-minio
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/minio.yaml
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                fi

            - name: Create pull request
              if: steps.update-minio.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "[dependency] Update the Minio subchart"
                body: "Updates the Minio subchart"
                base: main
                author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
                committer: "GitHub <noreply@github.com>"
                commit-message: Update minio
                labels: dependencies
                branch: chore/update-minio
                delete-branch: true

    updateGrafana:
        name: Update the Grafana version
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Updatecli
              uses: updatecli/updatecli-action@v2

            - name: Run Updatecli
              id: update-grafana
              run: |
                updatecli apply --config ${UPDATECLI_CONFIG_DIR}/grafana.yaml
                if ! git diff --exit-code > /dev/null; then
                  echo "changed=true" >> "${GITHUB_OUTPUT}"
                fi

            - name: Create pull request
              if: steps.update-grafana.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "[dependency] Update the Grafana version"
                body: "Updates the Grafana version"
                base: main
                author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
                committer: "GitHub <noreply@github.com>"
                commit-message: Update Grafana version
                labels: dependencies
                branch: chore/update-minio
                delete-branch: true
