---
name: helm-ci
on:
  pull_request:
    paths:
      - "charts/meta-monitoring/**"

env:
  CT_CONFIGFILE: charts/meta-monitoring/ct.yaml

jobs:
  call-lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Yaml
        run: make helm-lint
